baseURL = "/"
relativeURLS = true
languageCode = "en-us"
title = "The Codex Arundel"
theme = "archie"
copyright = "© Da Vinci"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4
googleAnalytics = "G-YE1LQE1TDC"

[author]
name = "Osborn Ghampson"

[params]
customcss = ["css/nav.css"]
favicon = "https://img.icons8.com/officel/16/000000/chevron-right.png"
og_image = "https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
# mode = "auto"
mode = "toggle"
useCDN = true
subtitle = "# __Computer Science, Physics, Electronics and Others__"
description = "A Blog"
code_copy_button = true
relatedPosts = false
katex = true

[taxonomies]
series = "series"
tags = "tags"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/osborngh"

[[params.social]]
name = "Gmail"
icon = "mail"
url = "mailto:osbornghdev@gmail.com"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Support"
url = "https://www.paypal.me/davincigh"
weight = 5
